---

- name: Add extras repository
  become: true
  shell: "yum-config-manager --enable extras"


- name: Install Java 11 via amazon-linux-extras packages
  become: true
  shell: "amazon-linux-extras install java-openjdk11 -y"