#artemis_name: apache-artemis-2.17.0
artemis_name: apache-artemis-2.18.0-SNAPSHOT
artemis_archive_name: "{{ artemis_name }}-bin.tar.gz"
artemis_download_dest: /tmp/{{ artemis_archive_name }}
artemis_download_url: https://archive.apache.org/dist/activemq/activemq-artemis/2.17.0/{{ artemis_archive_name }}
artemis_builded_dest:   /tmp/{{ artemis_archive_name }}

artemis_username: artemis

artemis_prometheus_exporter_url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.15.0/jmx_prometheus_javaagent-0.15.0.jar
