---

- name: Create promtail group
  group:
    name: promtail

- name: Create promtail user
  user:
    name: promtail
    group: promtail
    shell: /sbin/nologin
    system: "yes"
    groups: systemd-journal
    createhome: "no"
    state: present

- name: Download promtail
  unarchive:
    src: "{{ promtail_download_url }}"
    dest: /tmp
    remote_src: 'yes'
    mode: 0755

- name: Move promtail
  copy:
    src: "/tmp/promtail-linux-{{ promtail_arch }}"
    dest: "/usr/local/bin/promtail"
    mode: 0755
    owner: "promtail"
    group: "promtail"
    remote_src: true

- name: Delete node promtail tmp
  file:
    path: '/tmp/promtail-linux-{{ promtail_arch }}'
    state: absent

- name: Copy the promtail configuration
  template:
    src: promtail.yml.j2
    dest: /etc/promtail.yml
    mode: 0644

- name: Copy the promtail systemd unit
  template:
    src: promtail.service.j2
    dest: /etc/systemd/system/promtail.service
    mode: 0644

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Ensure promtail is running/restarted and enabled
  service:
    name: promtail
    state: "restarted"
    enabled: "true"